namespace ThermometerWRC
{
    [default_interface]
    runtimeclass Thermometer
    {
        Thermometer(Single startPoint);

        void AdjustTemperature(Single deltaFahrenheit);

        event Windows.Foundation.EventHandler<Single> TemperatureIsBelowFreezing;
    }
}